(require 'helm)
(require 'helm-config)
; (require 'helm-files)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-c f") 'helm-recentf)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x n") 'helm-for-files)
(global-set-key (kbd "C-h r") 'helm-info-emacs)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
;; (setq helm-locate-fuzzy-match t)
(setq helm-buffers-fuzzy-matching t)
(helm-mode 1)
